version: "3.8"

services:
  app-macos:
    build:
      context: .
      dockerfile: Dockerfile.macos  # Mac-specific Dockerfile
    ports:
      - "6080:80"
    security_opt:
      - seccomp=unconfined
    shm_size: 512m
    volumes:
      - ./catkin_ws:/home/ubuntu/catkin_ws
      - ./java_rosbridge:/home/ubuntu/java_rosbridge
      - ./mcapl:/home/ubuntu/mcapl
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=${TZ}
    stdin_open: true
    tty: true

  app-jetson:
    build:
      context: .
      dockerfile: Dockerfile.jetson  # Jetson-specific Dockerfile
    runtime: nvidia  # Enables GPU access
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "6080:80"
    security_opt:
      - seccomp=unconfined
    shm_size: 512m
    volumes:
      - ./catkin_ws:/home/ubuntu/catkin_ws
      - ./java_rosbridge:/home/ubuntu/java_rosbridge
      - ./mcapl:/home/ubuntu/mcapl
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=${TZ}
    stdin_open: true
    tty: true

