// Generated by gencpp from file gazebo_radiation_plugins/ConvertWorldBuilderModel.msg
// DO NOT EDIT!


#ifndef GAZEBO_RADIATION_PLUGINS_MESSAGE_CONVERTWORLDBUILDERMODEL_H
#define GAZEBO_RADIATION_PLUGINS_MESSAGE_CONVERTWORLDBUILDERMODEL_H

#include <ros/service_traits.h>


#include <gazebo_radiation_plugins/ConvertWorldBuilderModelRequest.h>
#include <gazebo_radiation_plugins/ConvertWorldBuilderModelResponse.h>


namespace gazebo_radiation_plugins
{

struct ConvertWorldBuilderModel
{

typedef ConvertWorldBuilderModelRequest Request;
typedef ConvertWorldBuilderModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConvertWorldBuilderModel
} // namespace gazebo_radiation_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_radiation_plugins::ConvertWorldBuilderModel > {
  static const char* value()
  {
    return "ca5346b14c3e8fe8c1488efbdb6aac5b";
  }

  static const char* value(const ::gazebo_radiation_plugins::ConvertWorldBuilderModel&) { return value(); }
};

template<>
struct DataType< ::gazebo_radiation_plugins::ConvertWorldBuilderModel > {
  static const char* value()
  {
    return "gazebo_radiation_plugins/ConvertWorldBuilderModel";
  }

  static const char* value(const ::gazebo_radiation_plugins::ConvertWorldBuilderModel&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_radiation_plugins::ConvertWorldBuilderModelRequest> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::ConvertWorldBuilderModel >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::ConvertWorldBuilderModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::ConvertWorldBuilderModel >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::ConvertWorldBuilderModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::ConvertWorldBuilderModelRequest> should match
// service_traits::DataType< ::gazebo_radiation_plugins::ConvertWorldBuilderModel >
template<>
struct DataType< ::gazebo_radiation_plugins::ConvertWorldBuilderModelRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::ConvertWorldBuilderModel >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::ConvertWorldBuilderModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_radiation_plugins::ConvertWorldBuilderModelResponse> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::ConvertWorldBuilderModel >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::ConvertWorldBuilderModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::ConvertWorldBuilderModel >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::ConvertWorldBuilderModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::ConvertWorldBuilderModelResponse> should match
// service_traits::DataType< ::gazebo_radiation_plugins::ConvertWorldBuilderModel >
template<>
struct DataType< ::gazebo_radiation_plugins::ConvertWorldBuilderModelResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::ConvertWorldBuilderModel >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::ConvertWorldBuilderModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_RADIATION_PLUGINS_MESSAGE_CONVERTWORLDBUILDERMODEL_H
