// Generated by gencpp from file gazebo_radiation_plugins/EnvironmentEvolver.msg
// DO NOT EDIT!


#ifndef GAZEBO_RADIATION_PLUGINS_MESSAGE_ENVIRONMENTEVOLVER_H
#define GAZEBO_RADIATION_PLUGINS_MESSAGE_ENVIRONMENTEVOLVER_H

#include <ros/service_traits.h>


#include <gazebo_radiation_plugins/EnvironmentEvolverRequest.h>
#include <gazebo_radiation_plugins/EnvironmentEvolverResponse.h>


namespace gazebo_radiation_plugins
{

struct EnvironmentEvolver
{

typedef EnvironmentEvolverRequest Request;
typedef EnvironmentEvolverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnvironmentEvolver
} // namespace gazebo_radiation_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_radiation_plugins::EnvironmentEvolver > {
  static const char* value()
  {
    return "e2797c797e620a950ba704492d72873b";
  }

  static const char* value(const ::gazebo_radiation_plugins::EnvironmentEvolver&) { return value(); }
};

template<>
struct DataType< ::gazebo_radiation_plugins::EnvironmentEvolver > {
  static const char* value()
  {
    return "gazebo_radiation_plugins/EnvironmentEvolver";
  }

  static const char* value(const ::gazebo_radiation_plugins::EnvironmentEvolver&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_radiation_plugins::EnvironmentEvolverRequest> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::EnvironmentEvolver >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::EnvironmentEvolverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::EnvironmentEvolver >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::EnvironmentEvolverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::EnvironmentEvolverRequest> should match
// service_traits::DataType< ::gazebo_radiation_plugins::EnvironmentEvolver >
template<>
struct DataType< ::gazebo_radiation_plugins::EnvironmentEvolverRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::EnvironmentEvolver >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::EnvironmentEvolverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_radiation_plugins::EnvironmentEvolverResponse> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::EnvironmentEvolver >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::EnvironmentEvolverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::EnvironmentEvolver >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::EnvironmentEvolverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::EnvironmentEvolverResponse> should match
// service_traits::DataType< ::gazebo_radiation_plugins::EnvironmentEvolver >
template<>
struct DataType< ::gazebo_radiation_plugins::EnvironmentEvolverResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::EnvironmentEvolver >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::EnvironmentEvolverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_RADIATION_PLUGINS_MESSAGE_ENVIRONMENTEVOLVER_H
