// Generated by gencpp from file gazebo_radiation_plugins/EnvironmentEvolverResponse.msg
// DO NOT EDIT!


#ifndef GAZEBO_RADIATION_PLUGINS_MESSAGE_ENVIRONMENTEVOLVERRESPONSE_H
#define GAZEBO_RADIATION_PLUGINS_MESSAGE_ENVIRONMENTEVOLVERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_radiation_plugins
{
template <class ContainerAllocator>
struct EnvironmentEvolverResponse_
{
  typedef EnvironmentEvolverResponse_<ContainerAllocator> Type;

  EnvironmentEvolverResponse_()
    : finished(false)  {
    }
  EnvironmentEvolverResponse_(const ContainerAllocator& _alloc)
    : finished(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;





  typedef boost::shared_ptr< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EnvironmentEvolverResponse_

typedef ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<std::allocator<void> > EnvironmentEvolverResponse;

typedef boost::shared_ptr< ::gazebo_radiation_plugins::EnvironmentEvolverResponse > EnvironmentEvolverResponsePtr;
typedef boost::shared_ptr< ::gazebo_radiation_plugins::EnvironmentEvolverResponse const> EnvironmentEvolverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator1> & lhs, const ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator2> & rhs)
{
  return lhs.finished == rhs.finished;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator1> & lhs, const ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_radiation_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2797c797e620a950ba704492d72873b";
  }

  static const char* value(const ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2797c797e620a95ULL;
  static const uint64_t static_value2 = 0x0ba704492d72873bULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_radiation_plugins/EnvironmentEvolverResponse";
  }

  static const char* value(const ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finished\n"
;
  }

  static const char* value(const ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnvironmentEvolverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_radiation_plugins::EnvironmentEvolverResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_RADIATION_PLUGINS_MESSAGE_ENVIRONMENTEVOLVERRESPONSE_H
