// Generated by gencpp from file gazebo_radiation_plugins/GenRandomEnvironmentalEffects.msg
// DO NOT EDIT!


#ifndef GAZEBO_RADIATION_PLUGINS_MESSAGE_GENRANDOMENVIRONMENTALEFFECTS_H
#define GAZEBO_RADIATION_PLUGINS_MESSAGE_GENRANDOMENVIRONMENTALEFFECTS_H

#include <ros/service_traits.h>


#include <gazebo_radiation_plugins/GenRandomEnvironmentalEffectsRequest.h>
#include <gazebo_radiation_plugins/GenRandomEnvironmentalEffectsResponse.h>


namespace gazebo_radiation_plugins
{

struct GenRandomEnvironmentalEffects
{

typedef GenRandomEnvironmentalEffectsRequest Request;
typedef GenRandomEnvironmentalEffectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenRandomEnvironmentalEffects
} // namespace gazebo_radiation_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects > {
  static const char* value()
  {
    return "1601fbc011dbf3b713e5f6ae36624db7";
  }

  static const char* value(const ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects&) { return value(); }
};

template<>
struct DataType< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects > {
  static const char* value()
  {
    return "gazebo_radiation_plugins/GenRandomEnvironmentalEffects";
  }

  static const char* value(const ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsRequest> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsRequest> should match
// service_traits::DataType< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects >
template<>
struct DataType< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsResponse> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsResponse> should match
// service_traits::DataType< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects >
template<>
struct DataType< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::GenRandomEnvironmentalEffects >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenRandomEnvironmentalEffectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_RADIATION_PLUGINS_MESSAGE_GENRANDOMENVIRONMENTALEFFECTS_H
