// Generated by gencpp from file gazebo_radiation_plugins/GenWorldsFromModels.msg
// DO NOT EDIT!


#ifndef GAZEBO_RADIATION_PLUGINS_MESSAGE_GENWORLDSFROMMODELS_H
#define GAZEBO_RADIATION_PLUGINS_MESSAGE_GENWORLDSFROMMODELS_H

#include <ros/service_traits.h>


#include <gazebo_radiation_plugins/GenWorldsFromModelsRequest.h>
#include <gazebo_radiation_plugins/GenWorldsFromModelsResponse.h>


namespace gazebo_radiation_plugins
{

struct GenWorldsFromModels
{

typedef GenWorldsFromModelsRequest Request;
typedef GenWorldsFromModelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenWorldsFromModels
} // namespace gazebo_radiation_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_radiation_plugins::GenWorldsFromModels > {
  static const char* value()
  {
    return "aab9442741bfdbb3be9f5e426f1408ca";
  }

  static const char* value(const ::gazebo_radiation_plugins::GenWorldsFromModels&) { return value(); }
};

template<>
struct DataType< ::gazebo_radiation_plugins::GenWorldsFromModels > {
  static const char* value()
  {
    return "gazebo_radiation_plugins/GenWorldsFromModels";
  }

  static const char* value(const ::gazebo_radiation_plugins::GenWorldsFromModels&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenWorldsFromModelsRequest> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenWorldsFromModels >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::GenWorldsFromModelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::GenWorldsFromModels >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenWorldsFromModelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::GenWorldsFromModelsRequest> should match
// service_traits::DataType< ::gazebo_radiation_plugins::GenWorldsFromModels >
template<>
struct DataType< ::gazebo_radiation_plugins::GenWorldsFromModelsRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::GenWorldsFromModels >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenWorldsFromModelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenWorldsFromModelsResponse> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenWorldsFromModels >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::GenWorldsFromModelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::GenWorldsFromModels >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenWorldsFromModelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::GenWorldsFromModelsResponse> should match
// service_traits::DataType< ::gazebo_radiation_plugins::GenWorldsFromModels >
template<>
struct DataType< ::gazebo_radiation_plugins::GenWorldsFromModelsResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::GenWorldsFromModels >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenWorldsFromModelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_RADIATION_PLUGINS_MESSAGE_GENWORLDSFROMMODELS_H
