// Generated by gencpp from file gazebo_radiation_plugins/GenYamlsFromWorld.msg
// DO NOT EDIT!


#ifndef GAZEBO_RADIATION_PLUGINS_MESSAGE_GENYAMLSFROMWORLD_H
#define GAZEBO_RADIATION_PLUGINS_MESSAGE_GENYAMLSFROMWORLD_H

#include <ros/service_traits.h>


#include <gazebo_radiation_plugins/GenYamlsFromWorldRequest.h>
#include <gazebo_radiation_plugins/GenYamlsFromWorldResponse.h>


namespace gazebo_radiation_plugins
{

struct GenYamlsFromWorld
{

typedef GenYamlsFromWorldRequest Request;
typedef GenYamlsFromWorldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenYamlsFromWorld
} // namespace gazebo_radiation_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_radiation_plugins::GenYamlsFromWorld > {
  static const char* value()
  {
    return "96e84490834f1029806f056f6761f002";
  }

  static const char* value(const ::gazebo_radiation_plugins::GenYamlsFromWorld&) { return value(); }
};

template<>
struct DataType< ::gazebo_radiation_plugins::GenYamlsFromWorld > {
  static const char* value()
  {
    return "gazebo_radiation_plugins/GenYamlsFromWorld";
  }

  static const char* value(const ::gazebo_radiation_plugins::GenYamlsFromWorld&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenYamlsFromWorldRequest> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenYamlsFromWorld >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::GenYamlsFromWorldRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::GenYamlsFromWorld >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenYamlsFromWorldRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::GenYamlsFromWorldRequest> should match
// service_traits::DataType< ::gazebo_radiation_plugins::GenYamlsFromWorld >
template<>
struct DataType< ::gazebo_radiation_plugins::GenYamlsFromWorldRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::GenYamlsFromWorld >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenYamlsFromWorldRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenYamlsFromWorldResponse> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::GenYamlsFromWorld >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::GenYamlsFromWorldResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::GenYamlsFromWorld >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenYamlsFromWorldResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::GenYamlsFromWorldResponse> should match
// service_traits::DataType< ::gazebo_radiation_plugins::GenYamlsFromWorld >
template<>
struct DataType< ::gazebo_radiation_plugins::GenYamlsFromWorldResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::GenYamlsFromWorld >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::GenYamlsFromWorldResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_RADIATION_PLUGINS_MESSAGE_GENYAMLSFROMWORLD_H
