// Generated by gencpp from file gazebo_radiation_plugins/Inspection.msg
// DO NOT EDIT!


#ifndef GAZEBO_RADIATION_PLUGINS_MESSAGE_INSPECTION_H
#define GAZEBO_RADIATION_PLUGINS_MESSAGE_INSPECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_radiation_plugins
{
template <class ContainerAllocator>
struct Inspection_
{
  typedef Inspection_<ContainerAllocator> Type;

  Inspection_()
    : location(0)  {
    }
  Inspection_(const ContainerAllocator& _alloc)
    : location(0)  {
  (void)_alloc;
    }



   typedef int16_t _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> const> ConstPtr;

}; // struct Inspection_

typedef ::gazebo_radiation_plugins::Inspection_<std::allocator<void> > Inspection;

typedef boost::shared_ptr< ::gazebo_radiation_plugins::Inspection > InspectionPtr;
typedef boost::shared_ptr< ::gazebo_radiation_plugins::Inspection const> InspectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_radiation_plugins::Inspection_<ContainerAllocator1> & lhs, const ::gazebo_radiation_plugins::Inspection_<ContainerAllocator2> & rhs)
{
  return lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_radiation_plugins::Inspection_<ContainerAllocator1> & lhs, const ::gazebo_radiation_plugins::Inspection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_radiation_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b70bb023a4b06746b026ccb2482d09be";
  }

  static const char* value(const ::gazebo_radiation_plugins::Inspection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb70bb023a4b06746ULL;
  static const uint64_t static_value2 = 0xb026ccb2482d09beULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_radiation_plugins/Inspection";
  }

  static const char* value(const ::gazebo_radiation_plugins::Inspection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 location\n"
;
  }

  static const char* value(const ::gazebo_radiation_plugins::Inspection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Inspection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_radiation_plugins::Inspection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_radiation_plugins::Inspection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "location: ";
    Printer<int16_t>::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_RADIATION_PLUGINS_MESSAGE_INSPECTION_H
