// Generated by gencpp from file gazebo_radiation_plugins/MassYamlLoader.msg
// DO NOT EDIT!


#ifndef GAZEBO_RADIATION_PLUGINS_MESSAGE_MASSYAMLLOADER_H
#define GAZEBO_RADIATION_PLUGINS_MESSAGE_MASSYAMLLOADER_H

#include <ros/service_traits.h>


#include <gazebo_radiation_plugins/MassYamlLoaderRequest.h>
#include <gazebo_radiation_plugins/MassYamlLoaderResponse.h>


namespace gazebo_radiation_plugins
{

struct MassYamlLoader
{

typedef MassYamlLoaderRequest Request;
typedef MassYamlLoaderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MassYamlLoader
} // namespace gazebo_radiation_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_radiation_plugins::MassYamlLoader > {
  static const char* value()
  {
    return "bf1b291db59c399c5c5b25859bd3e2e3";
  }

  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoader&) { return value(); }
};

template<>
struct DataType< ::gazebo_radiation_plugins::MassYamlLoader > {
  static const char* value()
  {
    return "gazebo_radiation_plugins/MassYamlLoader";
  }

  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoader&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_radiation_plugins::MassYamlLoaderRequest> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::MassYamlLoader >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::MassYamlLoaderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::MassYamlLoader >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoaderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::MassYamlLoaderRequest> should match
// service_traits::DataType< ::gazebo_radiation_plugins::MassYamlLoader >
template<>
struct DataType< ::gazebo_radiation_plugins::MassYamlLoaderRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::MassYamlLoader >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoaderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_radiation_plugins::MassYamlLoaderResponse> should match
// service_traits::MD5Sum< ::gazebo_radiation_plugins::MassYamlLoader >
template<>
struct MD5Sum< ::gazebo_radiation_plugins::MassYamlLoaderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_radiation_plugins::MassYamlLoader >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoaderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_radiation_plugins::MassYamlLoaderResponse> should match
// service_traits::DataType< ::gazebo_radiation_plugins::MassYamlLoader >
template<>
struct DataType< ::gazebo_radiation_plugins::MassYamlLoaderResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_radiation_plugins::MassYamlLoader >::value();
  }
  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoaderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_RADIATION_PLUGINS_MESSAGE_MASSYAMLLOADER_H
