// Generated by gencpp from file gazebo_radiation_plugins/MassYamlLoaderRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_RADIATION_PLUGINS_MESSAGE_MASSYAMLLOADERREQUEST_H
#define GAZEBO_RADIATION_PLUGINS_MESSAGE_MASSYAMLLOADERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_radiation_plugins
{
template <class ContainerAllocator>
struct MassYamlLoaderRequest_
{
  typedef MassYamlLoaderRequest_<ContainerAllocator> Type;

  MassYamlLoaderRequest_()
    : folder()  {
    }
  MassYamlLoaderRequest_(const ContainerAllocator& _alloc)
    : folder(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _folder_type;
  _folder_type folder;





  typedef boost::shared_ptr< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MassYamlLoaderRequest_

typedef ::gazebo_radiation_plugins::MassYamlLoaderRequest_<std::allocator<void> > MassYamlLoaderRequest;

typedef boost::shared_ptr< ::gazebo_radiation_plugins::MassYamlLoaderRequest > MassYamlLoaderRequestPtr;
typedef boost::shared_ptr< ::gazebo_radiation_plugins::MassYamlLoaderRequest const> MassYamlLoaderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator1> & lhs, const ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator2> & rhs)
{
  return lhs.folder == rhs.folder;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator1> & lhs, const ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_radiation_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf1b291db59c399c5c5b25859bd3e2e3";
  }

  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf1b291db59c399cULL;
  static const uint64_t static_value2 = 0x5c5b25859bd3e2e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_radiation_plugins/MassYamlLoaderRequest";
  }

  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string folder\n"
;
  }

  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.folder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MassYamlLoaderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_radiation_plugins::MassYamlLoaderRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "folder: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.folder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_RADIATION_PLUGINS_MESSAGE_MASSYAMLLOADERREQUEST_H
