// Generated by gencpp from file gazebo_radiation_plugins/MassYamlLoaderResponse.msg
// DO NOT EDIT!


#ifndef GAZEBO_RADIATION_PLUGINS_MESSAGE_MASSYAMLLOADERRESPONSE_H
#define GAZEBO_RADIATION_PLUGINS_MESSAGE_MASSYAMLLOADERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_radiation_plugins
{
template <class ContainerAllocator>
struct MassYamlLoaderResponse_
{
  typedef MassYamlLoaderResponse_<ContainerAllocator> Type;

  MassYamlLoaderResponse_()
    {
    }
  MassYamlLoaderResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MassYamlLoaderResponse_

typedef ::gazebo_radiation_plugins::MassYamlLoaderResponse_<std::allocator<void> > MassYamlLoaderResponse;

typedef boost::shared_ptr< ::gazebo_radiation_plugins::MassYamlLoaderResponse > MassYamlLoaderResponsePtr;
typedef boost::shared_ptr< ::gazebo_radiation_plugins::MassYamlLoaderResponse const> MassYamlLoaderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace gazebo_radiation_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_radiation_plugins/MassYamlLoaderResponse";
  }

  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MassYamlLoaderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::gazebo_radiation_plugins::MassYamlLoaderResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_RADIATION_PLUGINS_MESSAGE_MASSYAMLLOADERRESPONSE_H
