# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gazebo_radiation_plugins/WayP.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import gazebo_radiation_plugins.msg

class WayP(genpy.Message):
  _md5sum = "0b710348f6d9b37d2e3d0cc4a3be0ce8"
  _type = "gazebo_radiation_plugins/WayP"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 key
gazebo_radiation_plugins/Location pos

================================================================================
MSG: gazebo_radiation_plugins/Location
float64 x
float64 y
"""
  __slots__ = ['key','pos']
  _slot_types = ['int16','gazebo_radiation_plugins/Location']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       key,pos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WayP, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.key is None:
        self.key = 0
      if self.pos is None:
        self.pos = gazebo_radiation_plugins.msg.Location()
    else:
      self.key = 0
      self.pos = gazebo_radiation_plugins.msg.Location()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_h2d().pack(_x.key, _x.pos.x, _x.pos.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pos is None:
        self.pos = gazebo_radiation_plugins.msg.Location()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.key, _x.pos.x, _x.pos.y,) = _get_struct_h2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_h2d().pack(_x.key, _x.pos.x, _x.pos.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pos is None:
        self.pos = gazebo_radiation_plugins.msg.Location()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.key, _x.pos.x, _x.pos.y,) = _get_struct_h2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_h2d = None
def _get_struct_h2d():
    global _struct_h2d
    if _struct_h2d is None:
        _struct_h2d = struct.Struct("<h2d")
    return _struct_h2d
